### ISSUE TITLE
Add ability to change"Credit:" caption prefix.

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-image-credits#3]
Davin inquired about the ability to change the "Credit: " caption prefix. A setting for modifying that would work well. I think this is a reasonable request, and as a bonus it will make it so we don't need to generate language files for each language - they can just set the caption word to whatever they'd like.

**Comment by claudiulodro** [comment]
Note: this should also handle the case where the publisher wants to use no prefix.

**Comment by gamebits** [comment]
Added in https://github.com/Automattic/newspack-image-credits/pull/9. Closing.
