### ISSUE TITLE
PHP fatal error: Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-image-credits#6]
While using this plugin below critical error is thrown in error logs and leading to other issues

```
"PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Newspack_Image_Credits::add_credit_to_attachment_excerpts(), 1 passed in /wp-includes/class-wp-hook.php on line 292 and exactly 2 expected in /wp-content/plugins/newspack-image-credits/newspack-image-credits.php:173
```

**Comment by benlk** [comment]
Does your site have any custom functionality that references `Newspack_Image_Credits::add_credit_to_attachment_excerpts()` or is this happening within the plugin on its own?

Is this error appearing on a post, archive, or other sort of page?

**Comment by yogeshbeniwal** [comment]
This is not used anywhere else in the website.

So far this error is not shown on frontend pages, but affecting backend functionality such as Error in post publishing, Discourse plugin not able to cross post, Facebook instant article feed not working etc.

**Comment by yogeshbeniwal** [comment]
Closing this issue as plugin is merged with main plugin
