### ISSUE TITLE
Show placeholder image if no credit

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-image-credits#8]
Depending on what CMS publishers are coming from, their historical image credits may not be migrated. In those cases, displaying images without proper attribution can expose the publisher to legal liabilities.

It would be helpful if a placeholder image in the media library could be defined. If no credit is present for an image, the placeholder would then be displayed instead. This approach would allow the publisher to manually input credits as needed and have the copyrighted images reappear, without needing to remove the images from the media library or post body in the meantime.

**Comment by benlk** [comment]
Another option would be a filter on the image credit output, allowing site-specific code to draw from legacy sources of credit metadata in order to override this plugin's image credit if it's empty.
